---
title: "Schedule | David Dalpiaz"
output:
  html_document:
    lib_dir: libs
    self_contained: no
    theme: cosmo
    css: style.css
    includes:
      in_header: "header.html"
      before_body: "before.html"
---

For the **Spring 2018** semester I will be teaching at 10:00 AM and 11:00 AM on MWF. Outside of my listed office hours, the best way to reach me is [email](contact.html).

## Office Hours

- **Tuesday:** 11:00 AM - 11:59 AM
- **Wednesday:** 12:30 PM - 1:30 PM
- **Thursday:** 10:00 AM - 11:00 AM
- **Friday:** 12:30 PM - 1:30 PM

Currently, all office hours are "open" office hours, meaning you can stop by for class questions, advising, or really anything at all. If necessary, I may alter the schedule to specify certain times for certain activities.

If you need to schedule a meeting outside of these times, please send an email suggesting two possible times, on two different days. (A total of four suggested times.) Preference for time-slots directly adjacent to current office hours. Please also indicate a brief agenda for the meeting. If possible, I will also try to resolve the issue immediately via email.
